# Generated by Django 5.2.4 on 2025-08-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_wishlist_options_wishlist_added_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line1',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line2',
        ),
    ]
