# Generated by Django 5.2.4 on 2025-08-30 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_order_items_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_paid',
        ),
    ]
